// Code generated by [go run ./cmd/generate-libk8s "refs/heads/release-1.15"] (for k8s.io/cli-runtime commit cb4016b5ceb7a3ca63779ce26a8328c1a2c7208c). DO NOT EDIT.

module github.com/datawire/libk8s

go 1.12

require (
	cloud.google.com/go v0.34.0
	github.com/Azure/go-autorest v11.1.2+incompatible
	github.com/PuerkitoBio/purell v1.1.0
	github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
	github.com/davecgh/go-spew v1.1.1
	github.com/dgrijalva/jwt-go v0.0.0-20160705203006-01aeca54ebda
	github.com/docker/spdystream v0.0.0-20160310174837-449fdfce4d96
	github.com/emicklei/go-restful v1.1.4-0.20170410110728-ff4f55a20633
	github.com/evanphx/json-patch v0.0.0-20190203023257-5858425f7550
	github.com/ghodss/yaml v0.0.0-20180820084758-c7ce16629ff4
	github.com/go-openapi/jsonpointer v0.19.0
	github.com/go-openapi/jsonreference v0.19.0
	github.com/go-openapi/spec v0.17.2
	github.com/go-openapi/swag v0.17.2
	github.com/gogo/protobuf v0.0.0-20171007142547-342cbe0a0415
	github.com/golang/groupcache v0.0.0-20160516000752-02826c3e7903
	github.com/golang/protobuf v1.2.0
	github.com/google/btree v0.0.0-20160524151835-7d79101e329e
	github.com/google/go-cmp v0.3.0
	github.com/google/gofuzz v0.0.0-20170612174753-24818f796faf
	github.com/googleapis/gnostic v0.0.0-20170729233727-0c5108395e2d
	github.com/gophercloud/gophercloud v0.0.0-20190126172459-c818fa66e4c8
	github.com/gregjones/httpcache v0.0.0-20170728041850-787624de3eb7
	github.com/hashicorp/golang-lru v0.5.0
	github.com/imdario/mergo v0.3.5
	github.com/json-iterator/go v0.0.0-20180701071628-ab8a2e0c74be
	github.com/mailru/easyjson v0.0.0-20180823135443-60711f1a8329
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
	github.com/modern-go/reflect2 v1.0.1
	github.com/peterbourgon/diskv v2.0.1+incompatible
	github.com/pkg/errors v0.8.0
	github.com/spf13/cobra v0.0.0-20180319062004-c439c4fa0937
	github.com/spf13/pflag v1.0.1
	golang.org/x/crypto v0.0.0-20181025213731-e84da0312774
	golang.org/x/net v0.0.0-20190812203447-cdfb69ac37fc
	golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
	golang.org/x/sys v0.0.0-20190312061237-fead79001313
	golang.org/x/text v0.3.1-0.20181227161524-e6919f6577db
	golang.org/x/time v0.0.0-20161028155119-f51c12702a4d
	gopkg.in/inf.v0 v0.9.0
	gopkg.in/yaml.v2 v2.2.4
	k8s.io/api v0.0.0-20191004120003-3a12735a829a
	k8s.io/apimachinery v0.0.0-20191004115701-31ade1b30762
	k8s.io/cli-runtime v0.0.0-20191004123700-cb4016b5ceb7
	k8s.io/client-go v0.0.0-20191004120415-b2f42092e376
	k8s.io/klog v0.3.1
	k8s.io/kube-openapi v0.0.0-20190228160746-b3a7cee44a30
	k8s.io/utils v0.0.0-20190221042446-c2654d5206da
	sigs.k8s.io/kustomize v2.0.3+incompatible
	sigs.k8s.io/yaml v1.1.0
)
