version: 2

jobs:

  "build":
    docker:
      - image: golang:1.13rc2
    steps:
      - checkout
      - run: make clobber
      - run: make generate
      - run: |
          if test -n "$(git status -s)"; then
            git status
            exit 1
          fi
      - run: go build ./...
