// +build ignore

package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

var usageTemplate = template.Must(template.
	New("--help").
	Parse(`Usage: {{ .Arg0 }} VERSION\n", arg0)
Overwrite go.mod, to use the specified version of k8s.io/client-go

Examples:
    {{ .Arg0 }} v11.0.0                                  # tag
    {{ .Arg0 }} cbfe85d220c2dcb691a9ed0fa7f3c1bbb8bd7912 # commit
`))

var goModTemplate = template.Must(template.
	New("go.mod").
	Funcs(template.FuncMap{
		"trimPrefix": strings.TrimPrefix,
		"pkg2mod":    pkg2mod,
	}).
	Parse(`// Code generated by [{{ .Cmdline }}]. DO NOT EDIT.

module github.com/datawire/libk8s

go {{ trimPrefix .Godep.GoVersion "go" }}

require (
	k8s.io/client-go {{ .Version }}
{{- range $dep := .Godep.Deps }}
	{{ pkg2mod $dep.ImportPath }} {{ $dep.Rev }}
{{- end }}
)
`))

var pinGoTemplate = template.Must(template.
	New("pin.go").
	Parse(`// Code generated by [{{ .Cmdline }}]. DO NOT EDIT.

package libk8s

import (
{{- range $pkg := .Packages }}
	_ {{ printf "%q" $pkg }}
{{- end }}
)
`))

type Godep struct {
	ImportPath   string
	GoVersion    string
	GodepVersion string
	Packages     []string
	Deps         []struct {
		ImportPath string
		Rev        string
	}
}

func getGodep(version string) (Godep, error) {
	resp, err := http.Get("https://raw.githubusercontent.com/kubernetes/client-go/" + version + "/Godeps/Godeps.json")
	if err != nil {
		return Godep{}, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return Godep{}, fmt.Errorf("HTTP %v", resp.StatusCode)
	}

	godepBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return Godep{}, err
	}

	var godepStruct Godep
	if err := json.Unmarshal(godepBytes, &godepStruct); err != nil {
		return Godep{}, err
	}

	return godepStruct, err
}

func pkg2mod(pkg string) string {
	pkgParts := strings.Split(pkg, "/")
	switch {
	case strings.HasPrefix(pkg, "cloud.google.com/go/"):
		return "cloud.google.com/go"
	case strings.HasPrefix(pkg, "github.com/") && len(pkgParts) > 3:
		return strings.Join(pkgParts[:3], "/")
	case strings.HasPrefix(pkg, "golang.org/x/") && len(pkgParts) > 3:
		return strings.Join(pkgParts[:3], "/")
	case strings.HasPrefix(pkg, "gopkg.in/") && len(pkgParts) > 2:
		return strings.Join(pkgParts[:2], "/")
	case strings.HasPrefix(pkg, "k8s.io/") && len(pkgParts) > 2:
		return strings.Join(pkgParts[:2], "/")
	case strings.HasPrefix(pkg, "sigs.k8s.io/") && len(pkgParts) > 2:
		return strings.Join(pkgParts[:2], "/")
	default:
		return pkg
	}
}

func Main(arg0, version string) error {
	godep, err := getGodep(version)
	if err != nil {
		return fmt.Errorf("get Godep: %v", err)
	}

	// Do this in "." instead of os.TempDir ($TMPDIR or /tmp) so
	// that we don't have to worry about cross-filesystem moves
	// and can just use os.Rename.
	tmpdir, err := ioutil.TempDir(".", "tmp."+filepath.Base(strings.TrimSuffix(arg0, ".go")))
	if err != nil {
		return fmt.Errorf("tempdir: %v", err)
	}
	defer os.RemoveAll(tmpdir)

	goMod, err := os.OpenFile(filepath.Join(tmpdir, "go.mod"), os.O_CREATE|os.O_WRONLY, 0666)
	if err != nil {
		return err
	}

	err = goModTemplate.Execute(goMod, map[string]interface{}{
		"Cmdline": fmt.Sprintf("%s %q", arg0, version),
		"Version": version,
		"Godep":   godep,
	})
	goMod.Close()
	if err != nil {
		return fmt.Errorf("write go.mod: %v", err)
	}

	cmd := exec.Command("go", "list", "-deps", `-f={{ if and (not .Standard) (ne .Name "main") (gt (len .GoFiles) 0) }}{{ .ImportPath }}{{ end }}`, "k8s.io/client-go/...")
	cmd.Dir = tmpdir
	cmd.Stderr = os.Stderr
	allPkgsBytes, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("go list: %v", err)
	}
	var allPkgs []string
	for _, line := range strings.Split(string(allPkgsBytes), "\n") {
		if line == "" {
			continue
		}
		if strings.Contains(line, "/internal/") || strings.HasSuffix(line, "/internal") {
			continue
		}
		allPkgs = append(allPkgs, line)
	}
	sort.Strings(allPkgs)

	pin, err := os.OpenFile(filepath.Join(tmpdir, "pin.go"), os.O_CREATE|os.O_WRONLY, 0666)
	if err != nil {
		return err
	}

	err = pinGoTemplate.Execute(pin, map[string]interface{}{
		"Cmdline":  fmt.Sprintf("%s %q", arg0, version),
		"Packages": allPkgs,
	})
	pin.Close()
	if err != nil {
		return fmt.Errorf("write pin.go: %v", err)
	}

	cmd = exec.Command("go", "mod", "tidy")
	cmd.Dir = tmpdir
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("go mod tidy: %v", err)
	}

	if err := os.Rename(filepath.Join(tmpdir, "go.mod"), "go.mod"); err != nil {
		return err
	}
	if err := os.Rename(filepath.Join(tmpdir, "go.sum"), "go.sum"); err != nil {
		return err
	}
	if err := os.Rename(filepath.Join(tmpdir, "pin.go"), "pin.go"); err != nil {
		return err
	}

	return nil
}

func main() {
	arg0 := "go run ./hack/set-client-go-version.go"
	if len(os.Args) != 2 {
		_ = usageTemplate.Execute(os.Stderr, map[string]interface{}{
			"Arg0": arg0,
		})
		os.Exit(2)
	}
	if err := Main(arg0, os.Args[1]); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}
